---
# tasks file for build_aws_ami

- name: 'Create Build AMI Actions'
  include: create-build.yml
  when: build_aws_ami_action == 'create'

- name: 'Finalize Build AMI Actions'
  include: finalize-build.yml
  when: build_aws_ami_action == 'finalize'
